# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: EYC Pipeline

variables:
  - group: eyc-trunk-pkg-vars
  - name: IMAGE_NAME
    value: eycomply-worker
  - name: BASE_IMAGE_NAME
    value: eyc-app-worker 
 
steps:
- task: SSH@0
  displayName: 'Run shell commands on remote machine'
  inputs:
    sshEndpoint: 'EYC-Devops-Server'
    commands: 'echo $HOSTNAME'

- script: |
    mkdir -p ./packages && cd ./packages
    echo 'THIS IS QA16 YAML FILE'
    echo 'starting script execution'
    echo ${IMAGE_NAME} 
    echo ${ENV} 
    echo ${PORTAL} 
    echo ${BASE_IMAGE_NAME}
    echo ${PORTAL_NAME}
  displayName: 'echo variables'
